version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.7
        commands:
            - pip install --upgrade pip
        # Install dependencies needed for running the static analysis
            - pip install -r requirements.txt pylint
    pre_build:
        commands:
            - python --version
            - pylint --disable=E0611,E0401,E1101 *.py **/*.py
            - pylint $CODEBUILD_SRC_DIR/*.py
            - pylint $CODEBUILD_SRC_DIR/mypro/*.py
            - pylint $CODEBUILD_SRC_DIR/newapp/*.py
            
artifacts:
    files:
        - '**/*'
