# Generated by Django 2.1 on 2023-04-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20230413_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
